version: '1.1'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:jdbc: postgresql://db:5432/task-managment-system-db
      - SPRING_DATASOURCE_USERNAME=task-managment-system-db
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  db:
    image: 'postgres:14'
    container_name: db-postgres-container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER=task-managment-system-db
      POSTGRES_PASSWORD=123
