jwt:
  secret: "984hg493gh0439rthr0429augsu2309yh937gc763fe87t3f12723gf"
  lifetime: 10m

spring:
  application:
    name: Task Managment System

  datasource:
    url: "jdbc:postgresql://localhost:5432/task-managment-system-db"
    username: "postgres"
    password: "123"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

